Repository handcrafter/secret-admirer, pull requests merged in 2019-05, with the labels that each got.

#4 #1 : initial code base
  .gitignore
  README.md
  angular.json
  e2e/protractor.conf.js
  e2e/src/app.e2e-spec.ts
  e2e/src/app.po.ts
  e2e/tsconfig.e2e.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/assets/.gitkeep
  src/browserslist
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/favicon.ico
  src/index.html
  src/karma.conf.js
  src/main.ts
  src/polyfills.ts
  src/styles.scss
  src/test.ts
  src/tsconfig.app.json
  src/tsconfig.spec.json
  src/tslint.json
  tsconfig.json
  tslint.json
Labels: core

#12 Initial code base
  Members.js
  app.js
  middleware/logger.js
  package.json
  routes/api/members.js
  templates/about.html
  templates/css/style.css
  templates/index.html
Labels: core

#13 setup database and access through mongoose
  app.js
  templates/models/article.js
Labels: enhancement

#24 User management
  .gitignore
  README.md
  app.js
  data/.gitkeep
  package.json
  templates/login-success.html
  templates/login.html
  templates/models/Users.js
  test/retrieve_test.js
  test/save_test.js
  usermodel.js
Labels: core

#27 sign in logic
  Members.js
  app.js
  client/about.html
  client/css/style.css
  client/index.html
  client/login-success.html
  client/login.html
  client/signin.html
  db/database.js
  db/user.js
  middleware/logger.js
  package.json
  routes/api/members.js
  routes/login.js
  templates/models/Users.js
  templates/models/article.js
  test/retrieve_test.js
  test/save_test.js
  test/user.js
  usermodel.js
Labels: core, enhancement

#30 Setup react
  .gitignore
  README.md
  app.js
  client/css/index.css
  client/index.html
  client/index.jsx
  db/database.js
  package.json
  webpack.config.js
Labels: core

#31 Merging #30
  .gitignore
  README.md
  app.js
  client/css/index.css
  client/index.html
  client/index.jsx
  db/database.js
  package.json
  webpack.config.js
Labels: core
